### ISSUE TITLE
Can't vote on council election voting stage

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#1842]
The voting button won't show because the query used to show the amount of votes cast by the accounts fails.

So this query:
```gql
query {
  castVotesConnection(where: { electionRound: { cycleId_eq: 0 } }) {
    totalCount
  }
}
```
Fails with this error:
```json
{
  "errors": [
    {
      "message": "column castvote.undefined does not exist",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "castVotesConnection"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "message": "column castvote.undefined does not exist",
          "length": 116,
          "name": "QueryFailedError",
          "severity": "ERROR",
          "code": "42703",
          "position": "60",
          "file": "parse_relation.c",
          "line": "3349",
          "routine": "errorMissingColumn",
          "query": "SELECT COUNT(1) AS \"cnt\" FROM \"cast_vote\" \"castvote\" WHERE \"castvote\".\"undefined\" = $1 AND \"castvote\".\"deleted_at\" IS NULL",
          "parameters": [
            {
              "cycleId_eq": 0
            }
          ],
          "stacktrace": [
            "QueryFailedError: column castvote.undefined does not exist",
            "    at new QueryFailedError (/joystream/src/error/QueryFailedError.ts:9:9)",
            "    at PostgresQueryRunner.<anonymous> (/joystream/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:249:31)",
            "    at step (/joystream/node_modules/tslib/tslib.js:143:27)",
            "    at Object.throw (/joystream/node_modules/tslib/tslib.js:124:57)",
            "    at rejected (/joystream/node_modules/tslib/tslib.js:115:69)",
            "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

**Comment by thesan** [comment]
It looks like it's a problem with `xxxConnection` queries because this works:
```gql
castVotes(where: { electionRound: { cycleId_eq: 0 } }) { id }
```

but this doesn't:
```gql
candidatesConnection(where: { electionRound: { cycleId_eq: 0 } }) { totalCount }
```
