### ISSUE TITLE
[USERSNAP] App crash on reveal after cancelling former revealing

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2897]
**Taken at**: https://dao.joystream.org/#/election
**Fields**:
- Houston, we have a problem.: App crash on reveal after cancelling former revealing
- Comment: When i reveal a vote, then cancel signing, the next revealing fails.

```
1d9cc906246a16bda19a.js:2 TypeError: Cannot use &#39;in&#39; operator to search for &#39;getSnapshot&#39; in undefined
    at I (useActor.js:30:12)
    at useActor.js:63:20
    at kd (react-dom.production.min.js:219:180)
    at Cu (react-dom.production.min.js:259:160)
    at n.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at za (react-dom.production.min.js:122:325)
    at wu (react-dom.production.min.js:252:279)
    at fu (react-dom.production.min.js:243:371)
    at react-dom.production.min.js:123:115
    at n.unstable_runWithPriority (scheduler.production.min.js:18:343)


t.&lt;computed&gt; @ 1d9cc906246a16bda19a.js:2
useActor.js:30 Uncaught TypeError: Cannot use &#39;in&#39; operator to search for &#39;getSnapshot&#39; in undefined
    at I (useActor.js:30:12)
    at useActor.js:63:20
    at kd (react-dom.production.min.js:219:180)
    at Cu (react-dom.production.min.js:259:160)
    at n.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at za (react-dom.production.min.js:122:325)
    at wu (react-dom.production.min.js:252:279)
    at fu (react-dom.production.min.js:243:371)
    at react-dom.production.min.js:123:115
    at n.unstable_runWithPriority (scheduler.production.min.js:18:343)
```
- Feedback: l1dev

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/64c0b590-7534-412e-af0b-7f9ae4e816cb-annotated_9d5d0935-0fea-4f3c-83f0-4351ca609f0f.png?etag=c9ce5d97907345395d3ee6e2cf082376)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/64c0b590-7534-412e-af0b-7f9ae4e816cb-annotated_9d5d0935-0fea-4f3c-83f0-4351ca609f0f.png?etag=c9ce5d97907345395d3ee6e2cf082376)*

**Browser**: Chrome 100 (Linux)
**Screen size**: 1920x1080
**Browser size**: 2390x689
**[Open #222 in Usersnap](https://app.usersnap.com/l/feedback/fc56f14a-b66f-49d9-b3c3-5cebfd49222e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
should be fixed as we've done refactoring of the modal..
