### ISSUE TITLE
Optimize tests / code quality

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#3806]
TBD

```
Test Suites: 1 skipped, 119 passed, 119 of 120 total
Tests:       4 skipped, 854 passed, 858 total
Snapshots:   0 total
Time:        377.797 s, estimated 382 s
Ran all test suites.
```

```
    console.error
      Warning: Each child in a list should have a unique "key" prop.
            Check the render method of `SignTransactionModal`.

    console.error
      Warning: Each child in a list should have a unique "key" prop.
      
      Check the render method of `VerticalStaticStepper`

PASS test/council/modals/AnnounceCandidacyModal.test.tsx (72.094 s)
  ● Console

    console.warn
      Warning: Attempted to read state from uninitialized service '(machine)'. Make sure the service is started first.

      79 |
      80 | export const getSteps = (service: Interpreter<any, any, any, any>): Step[] => {
    > 81 |   return getStepsFromMachineAndState(service.machine, service.state)
         |                                                               ^
      82 | }

  console.error
      Warning: An update to AnnounceCandidacyModal inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act

    console.error
      Warning: Do not await the result of calling act(...) with sync logic, it is not a Promise.

  console.warn
      Cache data may be lost when replacing the group field of a WorkingGroupOpening object.
      
      To address this problem (which is not a bug in Apollo Client), either ensure all objects of type WorkingGroup have an ID or a custom merge function, or define a custom merge function for the WorkingGroupOpening.group field, so InMemo
ryCache can safely merge these objects:
      
        existing: {"__typename":"WorkingGroup","name":"forumWorkingGroup","budget":2393,"leaderId":"forumWorkingGroup-12"}
        incoming: {"__ref":"WorkingGroup:forumWorkingGroup"}
      
      For more information about these options, please refer to the documentation:
      
        * Ensuring entity objects have IDs: https://go.apollo.dev/c/generating-unique-identifiers
        * Defining custom merge functions: https://go.apollo.dev/c/merging-non-normalized-objects

      at Function.warn (../../node_modules/ts-invariant/lib/invariant.esm.js:35:27)
      at warnAboutDataLoss (../../node_modules/@apollo/client/cache/inmemory/writeToStore.js:396:26)

    console.error
      Warning: An update to AddNewProposalModal inside a test was not wrapped in act(...).    

    console.error
      Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input 
element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
          at input
          at fn (/home/debian/pioneer/node_modules/styled-components/src/models/StyledComponent.js:99:1)
          at label
          at fn (/home/debian/pioneer/node_modules/styled-components/src/models/StyledComponent.js:99:1)
          at div
          at fn (/home/debian/pioneer/node_modules/styled-components/src/models/StyledComponent.js:99:1)
          at fn (/home/debian/pioneer/packages/ui/src/common/components/forms/ToggleCheckbox.tsx:23:3)
          at fn (/home/debian/pioneer/node_modules/react-hook-form/src/controller.tsx:51:12)
          at fn (/home/debian/pioneer/packages/ui/src/common/components/forms/ToggleCheckbox.tsx:60:34)

console.error
      Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.
          at p
          at fn (/home/debian/pioneer/node_modules/styled-components/src/models/StyledComponent.js:99:1)
          at a
          at fn (/home/debian/pioneer/node_modules/styled-components/src/models/StyledComponent.js:99:1)
          at p
          at fn (/home/debian/pioneer/node_modules/styled-components/src/models/StyledComponent.js:99:1)
          at div
          at fn (/home/debian/pioneer/node_modules/styled-components/src/models/StyledComponent.js:99:1)
          at fn (/home/debian/pioneer/node_modules/react-hook-form/src/useFormContext.tsx:75:11)
          at div
          at fn (/home/debian/pioneer/node_modules/styled-components/src/models/StyledComponent.js:99:1)
          at div
          at fn (/home/debian/pioneer/node_modules/styled-components/src/models/StyledComponent.js:99:1)
          at div
          at fn (/home/debian/pioneer/node_modules/styled-components/src/models/StyledComponent.js:99:1)
          at section
          at fn (/home/debian/pioneer/node_modules/styled-components/src/models/StyledComponent.js:99:1)
          at div
          at fn (/home/debian/pioneer/node_modules/styled-components/src/models/StyledComponent.js:99:1)
          at fn (/home/debian/pioneer/packages/ui/src/common/components/Modal/Modal.tsx:59:25)
          at fn (/home/debian/pioneer/packages/ui/src/proposals/modals/AddNewProposal/AddNewProposalModal.tsx:66:36)

    console.error
      Transaction error: ExtrinsicFailed
      on network: ws://127.0.0.1:9944
      in block: 0x93XXX
      more details at: https://polkadot.js.org/apps/?rpc=ws://127.0.0.1:9944#/explorer/query/0x93XXX

    > 1 | export const error = (message?: any, ...optionalParams: any[]) => console.error(message, ...optionalParams)
        |                                                                           ^
      2 |
```
- Without checkout it be possible lower log level to info if tx are expected to fail.

**Comment by dmtrjsg** [comment]
That will be already covered by the tests that @thesan is updating as part of refactoring work.. Thank you for raising tho we share your sentiment 🤝
