### ISSUE TITLE
The "Displays approved votes" test sometime fails for no good reason

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#4370]
Not a timeout, which is confusing.

Log:
```
 | FAIL test/overview/components/ProposalsOverview.test.tsx (11.399 s)
 |   ● UI: Proposals overview › Proposal in Deciding stage › Displays approved votes
 | 
 |     Unable to find an element with the text: proposals.approvedVotes. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.
(...)
 |       120 |
 |       121 |     it('Displays approved votes', async () => {
 |     > 122 |       expect((await screen.findByText('proposals.approvedVotes')).nextSibling?.firstChild).toBeDefined()
 |           |                            ^
 |       123 |     })
 |       124 |
 |       125 |     it('Displays rejected votes', async () => {
 | 
 |       at waitForWrapper (../../node_modules/@testing-library/dom/dist/wait-for.js:187:27)
 |       at findByText (../../node_modules/@testing-library/dom/dist/query-helpers.js:101:12)
 |       at Object.<anonymous> (test/overview/components/ProposalsOverview.test.tsx:122:28)
```

Example: https://github.com/Joystream/pioneer/actions/runs/4829389026/jobs/8604373444?pr=4368

**Comment by dmtrjsg** [comment]
this one is a placeholder to keep watching if this happens again. Only happened once and not much impact.
